name: npm audit fix

on:
  workflow_dispatch: # manually

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    commit_title: "chore(deps): update npm dependencies"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ybiquitous/npm-audit-fix-action@e7e5e66fe613cd5e556db66eef24156b4bfa6134